-- Create user with full access to data schema
CREATE USER ${DATA_USER} WITH PASSWORD '${DATA_PASSWORD}';

-- Grant full access to data schema
GRANT ALL ON SCHEMA data TO ${DATA_USER};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA data TO ${DATA_USER};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA data TO ${DATA_USER};

-- Set default permissions for future objects
ALTER DEFAULT PRIVILEGES IN SCHEMA data GRANT ALL ON TABLES TO ${DATA_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA data GRANT ALL ON SEQUENCES TO ${DATA_USER};